### PR TITLE
Make GIT_SSH variable thread-safe

### PR DESCRIPTION
**Pull request by singpolyma**
Depends on https://github.com/usetint/ruby-git/pull/1

### CODE REVIEW

**Comment by singpolyma** [comment]
This and the associated ruby-git PR may need to be changed to make clones work... just realised my test may have worked because I have the key locally :P  need to double check

**Comment by singpolyma** [comment]
This has been re-tested against the latest ruby-git PR and definitely works now for clone.

**Comment by ericroberts** [comment]
@singpolyma tests are failing

**Comment by singpolyma** [comment]
@ericroberts updated Gemfile.lock, tests should pass now

**Comment by singpolyma** [comment]
Oh, there's another issue in a test. I'll fix that later

**Comment by singpolyma** [comment]
@ericroberts tests pass now

**Pull request merged**
